config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get 'user', to: 'user#new'
  post 'user', to: 'user#create'
  delete 'user/:id', to: 'user#destroy'

  get 'tickets', to: 'tickets#new'
  post 'tickets', to: 'tickets#create'
  delete 'tickets/:id', to: 'tickets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  ### Associations #################################################################################

  has_many :tickets, dependent: :destroy

  ### Validations ##################################################################################

  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "Must be a valid email" }
  validates :first_name, :last_name, :time_zone, presence: true

  ### Instance Methods #############################################################################

  def full_name
    "#{first_name} #{last_name}"
  end

  def user_name_id
    [full_name, id]
  end

  def self.all_users_name_id
    User.all.map {|u| u.user_name_id}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @tickets = Ticket.all
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to root_path, notice: "#{@ticket.title} was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    redirect_to root_path, status: :see_other, notice: "#{@ticket.title} was successfully deleted"
  end

  private

  def ticket_params
    params.require(:ticket).permit(
      :title,
      :description,
      :due_date,
      :status_id,
      :progress,
      :user_id
    )
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "#{@user.first_name} #{@user.last_name} was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other, notice: "#{@user.first_name} #{@user.last_name} was successfully deleted"
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :due_date_reminder,
      :due_date_reminder_interval,
      :due_date_reminder_time,
      :time_zone
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="d-flex flex-column align-items-center justify-content-center mt-4">
  <h1>Welcome on the home page!</h1>
  <h2>List of all users:</h2>
  <ul>
    <% @users.each do |user| %>
      <div class="d-flex justify-content-between align-items-center mb-3">
        <li><%= user.full_name %></li>
        <%= link_to "Delete", "user/#{user.id}", method: :delete, class: "btn btn-primary ms-3" %>
      </div>
    <% end %>
  </ul>

  <h2>List of all tickets:</h2>
  <ul>
    <% @tickets.each do |ticket| %>
      <div class="d-flex justify-content-between align-items-center mb-3">
        <li>
          <p>Title: <%= ticket.title %></p>
          <p>Description: <%= ticket.description %></p>
          <p>Due date: <%= ticket.due_date %></p>
          <p>Status: <%= ticket.status_id %></p>
          <p>Ticket progress: <%= ticket.progress %></p>
          <p>Person assigned to a ticket: <%= User.find(ticket.user.id).full_name %></p>
          <%= link_to "Delete", "tickets/#{ticket.id}", method: :delete, class: "btn btn-primary ms-3" %>
        </li>
      </div>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketReminder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/nav" %>

    <div class="container">
      <%= render partial: "shared/flash" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice].inspect %>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Users", user_path, class: "nav-link"%>
        <%= link_to "Tickets", tickets_path, class: "nav-link"%>
      </div>
    </div>
  </div>
</nav>

app/views/tickets/new.html.erb
<div class="d-flex flex-column align-items-center justify-content-center mt-4">
  <h1 class="mb-3">Create a ticket:</h1>
  <%= form_with model: @ticket, url: tickets_path, local: true do |form| %>

    <% if @ticket.errors.any? %>
      <div class="alert alert-danger">
        <% @ticket.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label "Title:" %>
      <%= form.text_field :title, class: "form-control", placeholder: 'Title' %>
    </div>
    <div class="mb-3">
      <%= form.label "Description:" %>
      <%= form.text_area :description, class: "form-control", placeholder: 'Description' %>
    </div>
    <div class="mb-3">
      <%= form.label "Date:" %>
      <%= form.date_field :due_date, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label "Set status:" %>
      <%= form.select(:status_id, [["Accepted", 0], ["Waiting", 1]], {}, {class: "form-select"}) %>
    </div>
    <div class="mb-3">
      <%= form.label "Set ticket progress:" %>
      <%= form.select(:progress, [["In progress", 0], ["In till", 1]], {}, {class: "form-select"}) %>
    </div>
    <div class="mb-3">
      <%= form.label "Assign user to a ticket:" %>
      <%= form.select(:user_id, User.all_users_name_id, {}, {class: "form-select"}) %>
    </div>
    <div class="w-full d-flex justify-content-center">
      <%= form.submit "Create ticket", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/user/new.html.erb
<div class="d-flex flex-column align-items-center justify-content-center mt-4">
  <h1 class="mb-3">Create a user:</h1>
  <%= form_with model: @user, url: user_path, local: true do |form| %>

    <% if @user.errors.any? %>
      <div class="alert alert-danger">
        <% @user.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label "Name:" %>
      <%= form.text_field :first_name, class: "form-control", placeholder: 'Name' %>
    </div>
    <div class="mb-3">
      <%= form.label "Surname:" %>
      <%= form.text_field :last_name, class: "form-control", placeholder: 'Surname' %>
    </div>
    <div class="mb-3">
      <%= form.label "Email address:" %>
      <%= form.text_field :email, class: "form-control", placeholder: 'email@email.com' %>
    </div>
    <div class="mb-3">
      <%= form.label "Set reminder:" %>
      <%= form.select(:due_date_reminder, [["Yes", true], ["No", false]], {}, {class: "form-select"}) %>
    </div>
    <div class="mb-3">
      <%= form.label "How many days back:" %>
      <%= form.number_field :due_date_reminder_interval, class: "form-control", placeholder: 'Days' %>
    </div>
    <div class="mb-3">
      <%= form.label "What time:" %>
      <%= form.time_field :due_date_reminder_time, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label "Select timezone:" %>
      <%= form.select(:time_zone, [["Berlin", "BE"], ["Chicago", "CHI"], ["Madrid", "MD"]], {}, {class: "form-select"}) %>
    </div>
    <div class="w-full d-flex justify-content-center">
      <%= form.submit "Create user", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>